url: "https://fluidsynth.org"
baseurl: "/"
title: "FluidSynth"
encoding: utf-8
exclude:
- Gemfile
- Gemfile.lock
- vendor/
keep_files:
- api
- api-1.x
paginate: 5
paginate_path: "/news/page:num/"
permalink: /news/:year/:month/:day/:title/
