libfluidsynth: seqbind.h File Reference
seqbind.h File Reference
Functions for binding sequencer objects to other subsystems.
Functions
FLUIDSYNTH_API fluid_seq_id_t fluid_sequencer_register_fluidsynth (fluid_sequencer_t *seq, fluid_synth_t *synth)
Registers a synthesizer as a destination client of the given sequencer.
FLUIDSYNTH_API int fluid_sequencer_add_midi_event_to_buffer (void *data, fluid_midi_event_t *event)
Transforms an incoming midi event (from a midi driver or midi router) to a sequencer event and adds it to the sequencer queue for sending as soon as possible.
Detailed Description
Functions for binding sequencer objects to other subsystems.
Function Documentation
fluid_sequencer_register_fluidsynth()
FLUIDSYNTH_API fluid_seq_id_t fluid_sequencer_register_fluidsynth (fluid_sequencer_t * seq, fluid_synth_t * synth)
Registers a synthesizer as a destination client of the given sequencer.
The synth is registered with the name "fluidsynth".
Parameters
seq Sequencer instance
synth Synthesizer instance
Returns
Sequencer client ID, or FLUID_FAILED on error.
Examples:
fluidsynth_arpeggio.c, and fluidsynth_metronome.c.
References fluid_event_get_bank(), fluid_event_get_channel(), fluid_event_get_control(), fluid_event_get_duration(), fluid_event_get_key(), fluid_event_get_pitch(), fluid_event_get_program(), fluid_event_get_sfont_id(), fluid_event_get_type(), fluid_event_get_value(), fluid_event_get_velocity(), fluid_event_noteoff(), FLUID_FAILED, fluid_log(), FLUID_PANIC, FLUID_SEQ_ALLNOTESOFF, FLUID_SEQ_ALLSOUNDSOFF, FLUID_SEQ_ANYCONTROLCHANGE, FLUID_SEQ_BANKSELECT, FLUID_SEQ_CHANNELPRESSURE, FLUID_SEQ_CHORUSSEND, FLUID_SEQ_CONTROLCHANGE, FLUID_SEQ_MODULATION, FLUID_SEQ_NOTE, FLUID_SEQ_NOTEOFF, FLUID_SEQ_NOTEON, FLUID_SEQ_PAN, FLUID_SEQ_PITCHBEND, FLUID_SEQ_PITCHWHHELSENS, FLUID_SEQ_PROGRAMCHANGE, FLUID_SEQ_PROGRAMSELECT, FLUID_SEQ_REVERBSEND, FLUID_SEQ_SUSTAIN, FLUID_SEQ_SYSTEMRESET, FLUID_SEQ_TIMER, FLUID_SEQ_UNREGISTERING, FLUID_SEQ_VOLUME, fluid_sequencer_count_clients(), fluid_sequencer_get_client_id(), fluid_sequencer_get_client_name(), fluid_sequencer_get_use_system_timer(), fluid_sequencer_process(), fluid_sequencer_register_client(), fluid_sequencer_send_at(), fluid_synth_all_sounds_off(), fluid_synth_bank_select(), fluid_synth_cc(), fluid_synth_channel_pressure(), fluid_synth_noteoff(), fluid_synth_noteon(), fluid_synth_pitch_bend(), fluid_synth_pitch_wheel_sens(), fluid_synth_program_change(), fluid_synth_program_select(), and fluid_synth_system_reset().
fluid_sequencer_add_midi_event_to_buffer()
FLUIDSYNTH_API int fluid_sequencer_add_midi_event_to_buffer (void * data, fluid_midi_event_t * event)
Transforms an incoming midi event (from a midi driver or midi router) to a sequencer event and adds it to the sequencer queue for sending as soon as possible.
Parameters
data The sequencer, must be a valid fluid_sequencer_t
event MIDI event
Returns
FLUID_OK or FLUID_FAILED
Since
1.1.0
References fluid_event_channel_pressure(), fluid_event_control_change(), fluid_event_noteoff(), fluid_event_noteon(), fluid_event_pitch_bend(), fluid_event_program_change(), fluid_event_set_dest(), fluid_event_system_reset(), FLUID_FAILED, fluid_midi_event_get_channel(), fluid_midi_event_get_control(), fluid_midi_event_get_key(), fluid_midi_event_get_pitch(), fluid_midi_event_get_program(), fluid_midi_event_get_type(), fluid_midi_event_get_value(), fluid_midi_event_get_velocity(), fluid_sequencer_get_tick(), and fluid_sequencer_send_at().