libfluidsynth: _fluid_sfont_t Struct Reference
_fluid_sfont_t Struct Reference
Virtual SoundFont instance structure.
Data Fields
void * data
User defined data.
unsigned int id
SoundFont ID.
int(* free)(fluid_sfont_t *sfont)
Method to free a virtual SoundFont bank.
char *(* get_name)(fluid_sfont_t *sfont)
Method to return the name of a virtual SoundFont.
fluid_preset_t *(* get_preset)(fluid_sfont_t *sfont, unsigned int bank, unsigned int prenum)
Get a virtual SoundFont preset by bank and program numbers.
void(* iteration_start)(fluid_sfont_t *sfont)
Start virtual SoundFont preset iteration method.
int(* iteration_next)(fluid_sfont_t *sfont, fluid_preset_t *preset)
Virtual SoundFont preset iteration function.
Detailed Description
Virtual SoundFont instance structure.
Field Documentation
free
int(* _fluid_sfont_t::free) (fluid_sfont_t *sfont)
Method to free a virtual SoundFont bank.
Parameters
sfont Virtual SoundFont to free.
Returns
Should return 0 when it was able to free all resources or non-zero if some of the samples could not be freed because they are still in use, in which case the free will be tried again later, until success.
Referenced by fluid_ramsfont_create_sfont().
get_name
char*(* _fluid_sfont_t::get_name) (fluid_sfont_t *sfont)
Method to return the name of a virtual SoundFont.
Parameters
sfont Virtual SoundFont
Returns
The name of the virtual SoundFont.
Referenced by fluid_ramsfont_create_sfont().
get_preset
fluid_preset_t*(* _fluid_sfont_t::get_preset) (fluid_sfont_t *sfont, unsigned int bank, unsigned int prenum)
Get a virtual SoundFont preset by bank and program numbers.
Parameters
sfont Virtual SoundFont
bank MIDI bank number (0-16383)
prenum MIDI preset number (0-127)
Returns
Should return an allocated virtual preset or NULL if it could not be found.
Referenced by fluid_ramsfont_create_sfont().
iteration_start
void(* _fluid_sfont_t::iteration_start) (fluid_sfont_t *sfont)
Start virtual SoundFont preset iteration method.
Parameters
sfont Virtual SoundFont
Starts/re-starts virtual preset iteration in a SoundFont.
Referenced by fluid_ramsfont_create_sfont().
iteration_next
int(* _fluid_sfont_t::iteration_next) (fluid_sfont_t *sfont, fluid_preset_t *preset)
Virtual SoundFont preset iteration function.
Parameters
sfont Virtual SoundFont
preset Caller supplied preset to fill in with current preset information
Returns
0 when no more presets are available, 1 otherwise
Should store preset information to the caller supplied preset structure and advance the internal iteration state to the next preset for subsequent calls.
Referenced by fluid_ramsfont_create_sfont().
The documentation for this struct was generated from the following file:
sfont.h