var FluidSettings =
[
    [ "Audio driver settings", "settings_audio.html", [
      [ "audio.driver", "settings_audio.html#settings_audio_driver", null ],
      [ "audio.periods", "settings_audio.html#settings_audio_periods", null ],
      [ "audio.period-size", "settings_audio.html#settings_audio_period-size", null ],
      [ "audio.realtime-prio", "settings_audio.html#settings_audio_realtime-prio", null ],
      [ "audio.sample-format", "settings_audio.html#settings_audio_sample-format", null ],
      [ "audio.alsa.device", "settings_audio.html#settings_audio_alsa_device", null ],
      [ "audio.coreaudio.device", "settings_audio.html#settings_audio_coreaudio_device", null ],
      [ "audio.dart.device", "settings_audio.html#settings_audio_dart_device", null ],
      [ "audio.dsound.device", "settings_audio.html#settings_audio_dsound_device", null ],
      [ "audio.file.endian", "settings_audio.html#settings_audio_file_endian", null ],
      [ "audio.file.format", "settings_audio.html#settings_audio_file_format", null ],
      [ "audio.file.name", "settings_audio.html#settings_audio_file_name", null ],
      [ "audio.file.type", "settings_audio.html#settings_audio_file_type", null ],
      [ "audio.jack.autoconnect", "settings_audio.html#settings_audio_jack_autoconnect", null ],
      [ "audio.jack.id", "settings_audio.html#settings_audio_jack_id", null ],
      [ "audio.jack.multi", "settings_audio.html#settings_audio_jack_multi", null ],
      [ "audio.jack.server", "settings_audio.html#settings_audio_jack_server", null ],
      [ "audio.oboe.id", "settings_audio.html#settings_audio_oboe_id", null ],
      [ "audio.oboe.sharing-mode", "settings_audio.html#settings_audio_oboe_sharing-mode", null ],
      [ "audio.oboe.performance-mode", "settings_audio.html#settings_audio_oboe_performance-mode", null ],
      [ "audio.oss.device", "settings_audio.html#settings_audio_oss_device", null ],
      [ "audio.portaudio.device", "settings_audio.html#settings_audio_portaudio_device", null ],
      [ "audio.pulseaudio.adjust-latency", "settings_audio.html#settings_audio_pulseaudio_adjust-latency", null ],
      [ "audio.pulseaudio.device", "settings_audio.html#settings_audio_pulseaudio_device", null ],
      [ "audio.pulseaudio.media-role", "settings_audio.html#settings_audio_pulseaudio_media-role", null ],
      [ "audio.pulseaudio.server", "settings_audio.html#settings_audio_pulseaudio_server", null ]
    ] ],
    [ "MIDI driver settings", "settings_midi.html", [
      [ "midi.autoconnect", "settings_midi.html#settings_midi_autoconnect", null ],
      [ "midi.driver", "settings_midi.html#settings_midi_driver", null ],
      [ "midi.realtime-prio", "settings_midi.html#settings_midi_realtime-prio", null ],
      [ "midi.portname", "settings_midi.html#settings_midi_portname", null ],
      [ "midi.alsa.device", "settings_midi.html#settings_midi_alsa_device", null ],
      [ "midi.alsa_seq.device", "settings_midi.html#settings_midi_alsa_seq_device", null ],
      [ "midi.alsa_seq.id", "settings_midi.html#settings_midi_alsa_seq_id", null ],
      [ "midi.coremidi.id", "settings_midi.html#settings_midi_coremidi_id", null ],
      [ "midi.jack.server", "settings_midi.html#settings_midi_jack_server", null ],
      [ "midi.jack.id", "settings_midi.html#settings_midi_jack_id", null ],
      [ "midi.oss.device", "settings_midi.html#settings_midi_oss_device", null ],
      [ "midi.winmidi.device", "settings_midi.html#settings_midi_winmidi_device", null ]
    ] ],
    [ "MIDI player settings", "settings_player.html", [
      [ "player.reset-synth", "settings_player.html#settings_player_reset-synth", null ],
      [ "player.timing-source", "settings_player.html#settings_player_timing-source", null ]
    ] ],
    [ "Shell (command line) settings", "settings_shell.html", [
      [ "shell.prompt", "settings_shell.html#settings_shell_prompt", null ],
      [ "shell.port", "settings_shell.html#settings_shell_port", null ]
    ] ],
    [ "Synthesizer settings", "settings_synth.html", [
      [ "synth.audio-channels", "settings_synth.html#settings_synth_audio-channels", null ],
      [ "synth.audio-groups", "settings_synth.html#settings_synth_audio-groups", null ],
      [ "synth.chorus.active", "settings_synth.html#settings_synth_chorus_active", null ],
      [ "synth.chorus.depth", "settings_synth.html#settings_synth_chorus_depth", null ],
      [ "synth.chorus.level", "settings_synth.html#settings_synth_chorus_level", null ],
      [ "synth.chorus.nr", "settings_synth.html#settings_synth_chorus_nr", null ],
      [ "synth.chorus.speed", "settings_synth.html#settings_synth_chorus_speed", null ],
      [ "synth.cpu-cores", "settings_synth.html#settings_synth_cpu-cores", null ],
      [ "synth.default-soundfont", "settings_synth.html#settings_synth_default-soundfont", null ],
      [ "synth.device-id", "settings_synth.html#settings_synth_device-id", null ],
      [ "synth.dynamic-sample-loading", "settings_synth.html#settings_synth_dynamic-sample-loading", null ],
      [ "synth.effects-channels", "settings_synth.html#settings_synth_effects-channels", null ],
      [ "synth.effects-groups", "settings_synth.html#settings_synth_effects-groups", null ],
      [ "synth.gain", "settings_synth.html#settings_synth_gain", null ],
      [ "synth.ladspa.active", "settings_synth.html#settings_synth_ladspa_active", null ],
      [ "synth.lock-memory", "settings_synth.html#settings_synth_lock-memory", null ],
      [ "synth.midi-channels", "settings_synth.html#settings_synth_midi-channels", null ],
      [ "synth.midi-bank-select", "settings_synth.html#settings_synth_midi-bank-select", null ],
      [ "synth.min-note-length", "settings_synth.html#settings_synth_min-note-length", null ],
      [ "synth.overflow.age", "settings_synth.html#settings_synth_overflow_age", null ],
      [ "synth.overflow.important", "settings_synth.html#settings_synth_overflow_important", null ],
      [ "synth.overflow.important-channels", "settings_synth.html#settings_synth_overflow_important-channels", null ],
      [ "synth.overflow.percussion", "settings_synth.html#settings_synth_overflow_percussion", null ],
      [ "synth.overflow.released", "settings_synth.html#settings_synth_overflow_released", null ],
      [ "synth.overflow.sustained", "settings_synth.html#settings_synth_overflow_sustained", null ],
      [ "synth.overflow.volume", "settings_synth.html#settings_synth_overflow_volume", null ],
      [ "synth.polyphony", "settings_synth.html#settings_synth_polyphony", null ],
      [ "synth.reverb.active", "settings_synth.html#settings_synth_reverb_active", null ],
      [ "synth.reverb.damp", "settings_synth.html#settings_synth_reverb_damp", null ],
      [ "synth.reverb.level", "settings_synth.html#settings_synth_reverb_level", null ],
      [ "synth.reverb.room-size", "settings_synth.html#settings_synth_reverb_room-size", null ],
      [ "synth.reverb.width", "settings_synth.html#settings_synth_reverb_width", null ],
      [ "synth.sample-rate", "settings_synth.html#settings_synth_sample-rate", null ],
      [ "synth.threadsafe-api", "settings_synth.html#settings_synth_threadsafe-api", null ],
      [ "synth.verbose", "settings_synth.html#settings_synth_verbose", null ]
    ] ]
];